//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmyService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class AlarmySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AlarmySettings defaultInstance = ((AlarmySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AlarmySettings())));
        
        public static AlarmySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The URL from which Alarmy receives new alarms.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The URL from which Alarmy receives new alarms.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ServiceURL {
            get {
                return ((string)(this["ServiceURL"]));
            }
            set {
                this["ServiceURL"] = value;
            }
        }
        
        /// <summary>
        /// The port to which Alarmy connects to the service.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The port to which Alarmy connects to the service.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public int SerivcePort {
            get {
                return ((int)(this["SerivcePort"]));
            }
            set {
                this["SerivcePort"] = value;
            }
        }
    }
}
